syntax = "proto3";

package book;

import "utils.proto";


message GetAllBookRequest {

}
message GetAllBookResponse{
     repeated Book books = 1;
}

message GetBookByAuthorRequest {
    string author = 1;
}

message GetBookByAuthorResponse {
    repeated Book books = 1;
}

message GetBookByIdRequest {
    string bookId = 1;
}
message GetBookByIdResponse {
    Book book = 1;
}
message AddBookRequest {
    string bookName = 1;
    Genre genre = 2;
    string authorId = 3;
    string published_date = 4;
}
message AddBookResponse {
    string message = 1;
}
message DeleteBookRequest {
    string bookId = 1;

}
message DeleteBookResponse {
    bool success = 1;
}

message UpdateBookRequest {
    string bookId = 1;
    string bookName = 2;
    Genre genre = 3;
    string published_date = 4;
}

message UpdateBookResponse {
    string message = 1;
}

service BookService {
    rpc AddBook (AddBookRequest) returns (AddBookResponse){};
    rpc DeleteBook (DeleteBookRequest) returns (DeleteBookResponse) {};
    rpc GetAllBook (GetAllBookRequest) returns (GetAllBookResponse){};
    rpc GetBookByAuthor (GetBookByAuthorRequest) returns (GetBookByAuthorResponse){};
    rpc GetBookById (GetBookByIdRequest) returns (GetBookByIdResponse){};
    rpc UpdateBook (UpdateBookRequest) returns (UpdateBookResponse) {};
}