syntax = "proto3";

package payment;


enum PaymentStatus {
    PENDING = 1;
    COMPLETED = 2;
    FAILED = 3;
    REFUNDED = 4;
}

message Payment{
     string id = 1;
     string orderId = 2;
     double totalAmount = 3;
     PaymentStatus paymentStatus = 4;
     string paymentIntendId = 5;
     string paymentMethodId = 6;
}


message InitiateOrderPaymentRequest {
    string orderId = 1;
}

message InitiateOrderPaymentResponse {
        Payment paymentDetails = 1;
        bool success = 2;
        string bookName = 3;
        int32 quantity = 4;
        double price = 5;
}

message PaymentSuccessRequest{
    string orderId = 1;
    string paymentId = 2;
    string paymentIntendId = 3;
    string paymentMethodId = 4;
}
message PaymentSuccessResponse {
    bool success = 1;
    string message = 2;
}

message PaymentCancelRequest{
    string orderId = 1;
    string paymentId = 2;

}

message PaymentCancelResponse {
  bool success = 1;
  string message = 2;
}


message GetPaymentDetailsByIdRequest {
   string paymentId = 1;
}

message GetPaymentDetailsByIdResponse {
    map<string,Payment> payment = 1;
    string bookName = 2;
    string customerName = 3;
    string paymentMethod = 4;
}



service PaymentService {
    
    rpc InitiateOrderPayment(InitiateOrderPaymentRequest) returns (InitiateOrderPaymentResponse) {};
    rpc PaymentSuccess(PaymentSuccessRequest) returns (PaymentSuccessResponse) {};
    rpc PaymentCancel (PaymentCancelRequest) returns (PaymentCancelResponse) {};
    rpc GetPaymentDetailsById (GetPaymentDetailsByIdRequest) returns (GetPaymentDetailsByIdResponse) {};
}


