syntax = "proto3";

package payment;


enum PaymentStatus {
    PENDING = 1;
    COMPLETED = 2;
    FAILED = 3;
    REFUNDED = 4;
}

message Payment{
     string id = 1;
     string orderId = 2;
     double totalAmount = 3;
     PaymentStatus paymentStatus = 4;
}


message InitiateOrderPaymentRequest {
    string orderId = 1;
}

message InitiateOrderPaymentResponse {
        Payment paymentDetails = 1;
        bool success = 2;
        string bookName = 3;
        int32 quantity = 4;
        double price = 5;
}

message PaymentRequest{
    string orderId = 1;
    string paymentId = 2;
}

message PaymentResponse {
  bool success = 1;
  string message = 2;
}


service PaymentService {
    
    rpc InitiateOrderPayment(InitiateOrderPaymentRequest) returns (InitiateOrderPaymentResponse) {};
    rpc PaymentSuccess(PaymentRequest) returns (PaymentResponse) {};
    rpc PaymentCancel (PaymentRequest) returns (PaymentResponse) {};
}


