name: Run test programs workflows

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  schedule:
    - cron: "28 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies for gateway
        run: |
          echo "Changing directory to gateway"
          cd gateway && echo "Installing Dependencies"
          npm install

      - name: Prepare artifacts for gateway
        uses: actions/upload-artifact@v4
        with:
          name: gateway_node_modules
          path: gateway/node_modules

      - name: Install dependencies for server
        run: |
          echo "changing the directory to server and installing dependencies"
          cd server
          npm install

      - name: Verify node_modules existence
        run: |
          echo "Verifying node_modules exists"
          ls -l server/node_modules 
          
      - name: Upload node_modules as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server_node_modules
          path: server/node_modules  

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  

      - name: Download node_modules for gateway
        uses: actions/download-artifacts@v4
        with:
          name: gateway_node_modules
          path: gateway/node_modules

      - name: Download node_modules from uploaded artifact
        uses: actions/download-artifact@v4
        with:
          name: server_node_modules  
          path: server/node_modules  

      - name: Test to run a function
        run: |
          echo "Running tests..."
          cd server
          npm install -D jest
          npm run 
          npm run test
