name: Run test programs workflows

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo "changing the directory to server and installing dependencies"
          cd server
          npm install

      - name: Verify node_modules existence
        run: |
          echo "Verifying node_modules exists"
          ls -l server/node_modules  # List the directory to confirm node_modules is created
          
      # - name: Upload node_modules as artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: node_modules
      #     path: server/node_modules

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Downloading node_modules from uploaded artifact
        uses: actions/download-artifact@v3
        with:
          name: node_modules
          path: server/node_modules

      - name: Test to run a function
        run: npm run test
