# .github/workflows/test.yml

name: Run test programs workflows

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo "changing the directory to server and installing dependencies"
          cd server
          npm install

      - name: Upload node modules as artifacts
        uses: actions/upload-artifacts@v3
        with:
          name: node_modules
          path: server/node_modules

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Downloading node_modules from uploaded artifacts
        uses: actions/download-artifacts@v3
        with:
          name: node_modules
          path: server/node_modules

      - name: Test to run a function
        run: npm run test
